---
galaxy_info:
  author: Shack Of No Return
  description: Create and manage Proxmox VE LXC containers
  license: MIT

  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - bookworm

dependencies: []
