---
- name: Validate Proxmox container variables
  ansible.builtin.include_tasks:
    file: validate.yml

- name: Create Proxmox container
  ansible.builtin.include_tasks:
    file: create.yml

- name: Configure container state
  ansible.builtin.include_tasks:
    file: start.yml

- name: Wait for container availability
  ansible.builtin.include_tasks:
    file: wait.yml
  when:
    - proxmox_container_state == "started"
    - proxmox_container_wait_for_ssh | bool
