---
# Proxmox API
proxmox_api_host: ""
proxmox_api_port: 8006
proxmox_api_user: "root@pam"
proxmox_api_password: ""
proxmox_validate_certs: false


# Proxmox node
proxmox_node: ""


# Container identity
proxmox_container_vmid:
proxmox_container_hostname: ""

proxmox_container_description: ""


# Template
# local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst
proxmox_container_template_storage: "local"
proxmox_container_template: ""


# Storage
proxmox_container_storage: "local-lvm"
proxmox_container_disk_size: 8


# CPU
proxmox_container_cores: 2
proxmox_container_cpus: 1
proxmox_container_cpuunits: 1024


# Memory
proxmox_container_memory: 2048
proxmox_container_swap: 512


# Authentication inside container
proxmox_container_password: ""
proxmox_container_ssh_key: ""


# Network
proxmox_container_bridge: "vmbr0"
proxmox_container_ip: ""
proxmox_container_prefix: 24
proxmox_container_gateway: ""
proxmox_container_nameserver: ""
proxmox_container_searchdomain: ""


# Features
proxmox_container_features:
  - nesting=1


# Security
proxmox_container_unprivileged: true
proxmox_container_firewall: true
proxmox_container_protection: false


# Boot
proxmox_container_onboot: true
proxmox_container_startup:
  - order=10


# OS
proxmox_container_ostype: auto
proxmox_container_timezone: host


# Tags
proxmox_container_tags:
  - ansible


# Optional hooks
proxmox_container_hookscript: ""


# Additional mounts
proxmox_container_mounts: []


# Lifecycle
proxmox_container_state: started
proxmox_container_force: false
proxmox_container_update: true


# Timeout
proxmox_container_timeout: 120


# Wait
proxmox_container_wait_for_ssh: true
proxmox_container_wait_timeout: 600
